name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        - For questions, ask in [Discussions](https://github.com/react-icons/react-icons/discussions/categories/q-a)
        - Please check if there is already a similar issue. [Issues](https://github.com/react-icons/react-icons/issues)
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: repo-url
    attributes:
      label: Minimal sample repository URL
      description: |
        Gist/GitHub URL.
        Please provide a repository that includes only the minimal packages and code necessary to reproduce the issue.
        If it's happening on the demo site, its URL.
      placeholder: "https://github.com/..."
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: Package version
      description: The version of react-icons used in the project
      placeholder: "vX.Y.Z"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
